import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/register";
import { Global } from "@/assets/styles/Global";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  manifest: "/manifest.json",
  title: "Electrify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Global />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
